# Attempt at trying to run a workflow for releasing new versions and to learn actions 
# Seems to be a recent checkout issue: https://github.com/actions/checkout/issues/417

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    #paths:
    #  - "**.go"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: "Release new minor semantic version"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
          token: ${{ secrets.GH_SECRET }}

      - name: semver
        id: semver
        uses: paulhatch/semantic-version@v4.0.2
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}-${increment}"
          # #-${increment}"
          # Optional path to check for changes. If any changes are detected in the path the
          # 'changed' output will true. Enter multiple paths separated by spaces.
          change_path: "."
          # Named version, will be used as suffix for name version tag
          namespace: ""
          # Indicate whether short tags like 'v1' should be supported. If false only full
          # tags like 'v1.0.0' will be recognized.
          short_tags: false
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: true
      #- name: create release
      #  id: create_release
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GH_SECRET }} # This token is provided by Actions, you do not need to create your own token
      #  with:
      #    tag_name: v0.2.0-1
      #    release_name: v0.2.0-1
      #    body: |
      #      **Full Changelog**: https://github.com/gsoc2/gsoc2-shared/compare/v0.1.14...v0.1.15
      #    draft: true 
      #    prerelease: true 
